### ISSUE TITLE
Pretrained model links are wrong

### ISSUE THREAD

**Issue by aanna0701** [wxzs5/direct-pretraining#5]
Thank you very much for revealing the great research.

I want to use your work as a reference for my research.

Currently published pretrained links do not work.

I need Mask RCNN w/ Swin [Direct(P1x)-1x] and Mask RCNN w/ Swin [Direct(P3x)-1x]

Could you please edit the link?

**Comment by wxzs5** [comment]
Due to the Drive server temporarily unavailable now, it may need some time to recover.

We also have uploaded some models to Google Drive temporarily , you can download from:  

[Mask Swin P1x-1x](https://drive.google.com/file/d/18JI6MEDsrtjUDTGQfBXCeFUVyX4ITbj4/view?usp=sharing)  

[Mask Swin P3x-1x](https://drive.google.com/file/d/19yER3NgfKZVePxDIQzZ6xxAy8X9ouJxe/view?usp=sharing)

**Comment by aanna0701** [comment]
Thank you very much for your reply.

your work is very awesome!

have a nice day.
